version: '3.3'

services:
  vending-app:
    build:
      dockerfile: Dockerfile
    pull_policy: always
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - "8080:80"